config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
   validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
   before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
    @blog = Blog.new(blog_params)
    else
    @blog = Blog.new
    end

  end

  def create
    @blog = Blog.new(blog_params)
   if @blog.save
     redirect_to blogs_path, notice: "ブログを作成しました！"
   else
     render 'new'
   end
 end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
     @blog = Blog.find(params[:id])
  end

  def confirm
  @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end



  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
     @blog = Blog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログイン成功"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウト成功"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamApp180803</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "サインアップ", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, loca: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>登録メールアドレス:<%= @user.email %></p>